#服务地址
server:
  port: 8085
spring:
  application:
    name: zhahuo-search-server
  datasource:
    url: jdbc:mysql://localhost:3306/zhahuo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
#ureka连接配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${spring.application.name}:${server.port}
